# --- Build Stage ---
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copy all files
COPY . .

# Build the project (skip default src paths)
RUN mvn -B compile assembly:single -DdescriptorId=jar-with-dependencies

# --- Run Stage ---
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the jar generated by assembly plugin
COPY --from=build /app/target/*-jar-with-dependencies.jar app.jar

CMD ["java", "-jar", "app.jar"]

